### ISSUE TITLE
你把Library这个目录排除了，就没法正常使用了

### ISSUE THREAD

**Issue by coco5666** [houko/Tank#1]
![image](https://user-images.githubusercontent.com/57277047/70847233-16d55580-1e9d-11ea-9d2c-b13bae6f3b0b.png)

**Comment by coco5666** [comment]
是main.unity吗？

**Comment by coco5666** [comment]
在Library目录下建个`LastSceneManagerSetup.txt`，文件中写入如下内容即可正常运行
```bash
sceneSetups:
- path: Assets/Scenes/Main.unity
  isLoaded: 1
  isActive: 1
```

**Comment by houko** [comment]
> 在Library目录下建个`LastSceneManagerSetup.txt`，文件中写入如下内容即可正常运行
> 
> ```shell
> sceneSetups:
> - path: Assets/Scenes/Main.unity
>   isLoaded: 1
>   isActive: 1
> ```

我每次都是手动选择main.sence启动的。。 谢谢 我跟进一下
或者老哥你提个PR，我把合并进去

**Comment by houko** [comment]
> > 在Library目录下建个`LastSceneManagerSetup.txt`，文件中写入如下内容即可正常运行
> > ```shell
> > sceneSetups:
> > - path: Assets/Scenes/Main.unity
> >   isLoaded: 1
> >   isActive: 1
> > ```
> 
> 我每次都是手动选择main.sence启动的。。 谢谢 我跟进一下
> 或者老哥你提个PR，我把合并进去

己添加场景配置
